#!/usr/bin/env bash

INSTALL_VERSION="0.9.7"
INSTALL_PATH=$HOME

mkdir -p $INSTALL_PATH
cd /tmp && curl -L -O https://github.com/spider-network/ubuntu-vm-basics/archive/$INSTALL_VERSION.tar.gz
cd /tmp && tar -xvf $INSTALL_VERSION.tar.gz

rm -rf $INSTALL_PATH/ubuntu-vm-basics*

cp -r /tmp/ubuntu-vm-basics-$INSTALL_VERSION $INSTALL_PATH
cd $INSTALL_PATH && ln -sf ubuntu-vm-basics-$INSTALL_VERSION ubuntu-vm-basics

rm /tmp/$INSTALL_VERSION.tar.gz && rm -rf /tmp/ubuntu-vm-basics-*

echo ""
echo -e "Go to '\033[32mcd $INSTALL_PATH/ubuntu-vm-basics\033[00m' and execute the install script '\033[32m./installer\033[00m'"
