#!/usr/bin/env bash

# Folders
SCRIPT=$(readlink -f "$0")
SERVER_CONFIG_DIR=`dirname "$SCRIPT"`
SERVER_CONFIG_INSTALL_DIR=$SERVER_CONFIG_DIR
SERVER_CONFIG_VENDOR_DIR=$SERVER_CONFIG_INSTALL_DIR/vendor

# Programm versions
BUNDLER_VERSION=1.2.3    # http://rubygems.org/gems/bundler

# Function to install chef
source ~/.rvm/scripts/rvm && cd $SERVER_CONFIG_VENDOR_DIR && sudo gem install bundler-$BUNDLER_VERSION.gem --local --no-rdoc --no-ri
source ~/.rvm/scripts/rvm && cd $SERVER_CONFIG_INSTALL_DIR && bundle install --local
